### ISSUE TITLE
유닛 공격 우선순위 및 이동

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#103]
두 유닛이 시간차로 때림 -> 맞는 한 유닛은 공격하러 이동하는데 계속 어그로 핑퐁됨

정상?

**Comment by boyism80** [comment]
계속 갱신하면 내 공격 시점에 내가 때릴 수 없는 범위의 유닛이 가장 최근 갱신되었을 때 문제가 발생할 것 같음
날 때린 유닛들을 해시셋에 저장해뒀다가 내가 공격하는 시점에 (현재 설정된 타겟이 범위 안에 없을 때) 해당 유닛들 중 가장 가까운 유닛을 찾고 아니면(현재 설정된 유닛이 범위 안에 있을 때) 기존 타겟 그대로 유지  
그 이후 즉시 해시셋 초기화하면 될듯?

**Comment by suhyeokkim** [comment]
범위=공격범위

**Comment by suhyeokkim** [comment]
https://github.com/KG-Crash/crash/commit/923b518ba3fab0c38c8561c719fd9d5986210012

**Comment by suhyeokkim** [comment]
유닛은 날 때린놈만 공격, 아니면idle 일 때 찾음
