### ISSUE TITLE
Ready와 동기화

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#121]
Ready 리스폰스 받은 이후에 Frame 업데이트

해결방안 : 서버에서 상태저장

**Comment by suhyeokkim** [comment]
프로토콜 틀은 되어있으니 클라쪽도 동시에 함

**Comment by suhyeokkim** [comment]
이거 하면 #125 해결?

**Comment by boyism80** [comment]
> 이거 하면 #125 해결?

dd

**Comment by suhyeokkim** [comment]
순차적으로 들어왔을 때, 브로드캐스팅 하는거 확인 please

**Comment by boyism80** [comment]
https://github.com/KG-Crash/crash/blob/763676c4954b32de37f0b872912bb425d08bffbb/server/src/model/user/user.go#L280

https://github.com/KG-Crash/crash/blob/763676c4954b32de37f0b872912bb425d08bffbb/server/src/model/room/room.go#L374

이 부분 수정해놓도록 하겠음

**Comment by boyism80** [comment]
https://github.com/KG-Crash/crash/blob/187492666c998e64d93ac96ca1e814f2bca25895/server/src/model/user/user.go#L298

Ready 메시지를 Room에 보내야함.. 수정해놓겠음
