### ISSUE TITLE
동기화 샘플

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#123]
1. 클라이언트에서 특정 키 입력시 해당 플레이어(본인)의 특정한 위치에 유닛 스폰
스폰되는 정보를 액션큐에 담아서 동기화
함께 하는 플레이어에게 문제 없이 보이는지 확인

2. 채팅

3. 액션 일부러 안보내기 기능?

**Comment by suhyeokkim** [comment]
대충 끝남ㅋ
