### ISSUE TITLE
클라이언트 동기화 버그

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#125]
마지막에 들어온 유저(채승현)의
input frame : 9
output frame : 6
의 상태로 행 걸림(waitPacket = true)

**Comment by suhyeokkim** [comment]
먼저 로딩된 클라이언트가 다른 씬 로드가 끝나기 전에 프레임 패킷 보내서 정보가 유실됨

**Comment by boyism80** [comment]
원인 찾아서 해결중이므로 이슈 닫음
