### ISSUE TITLE
일시정지

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#130]
- Action 에 실어서 보냄
- 받으면 어떻게 처리할지 고민

**Comment by suhyeokkim** [comment]
일반적인 일시정지 걍 사용 가능해야함

**Comment by suhyeokkim** [comment]
겜중 -> 일시정지, 일시정지 -> 겜중 동일

- 패킷을 한놈이 보내면, 전부 해당 턴에 브로드캐스팅 받음.
- 이 때 모두 받게 되면 전부 다 멈춤/다시시작
    - 멈추게 되면 일단 저장은 해놓고, 다시시작 때 바로 처리해버리기

**Comment by suhyeokkim** [comment]
앞으로의 방법에 따라 조금 달라질 수 있음. paused 를 바꿔서 Unit/Projectile 클래스의 Update 를 호출 안할 수도 있음.

근데  OnUpdateFrame 내에서 모든 유닛, 투사체, 업그레이드 등을 다 처리하면 그냥 OnUpdateAction 에서 paused 를 조작하면 됨. 일단 심플하게 OnUpdateAction 에서 해보고, 나중에 고민하면서 바꿔보는 걸로

**Comment by suhyeokkim** [comment]
#138 이후에 작업 재개
