### ISSUE TITLE
#142 액션 구현

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#143]
각자 맡은 역할에 최선을 다해주세요.

**Comment by suhyeokkim** [comment]
#142

**Comment by suhyeokkim** [comment]
pause 는 있는거 정리만하고, speed 는 그대로 적용, heartbeat 로 사용하던거 enum 추가 + 세팅

치트는 InGameChat 으로 오는거 그대로 적용해서 네트워크 모드와 상관없이 그대로 적용함

**Comment by suhyeokkim** [comment]
#145 에서 디코할 때 말한대로, 액션 핸들러에서 처리하게 바꿈.
