### ISSUE TITLE
투사체 유닛과 같은 방식으로 재구현

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#151]
LogicalObject를 상속받는 유닛과 투사체로 구현
IActor를 구현하는 UnitActor와 ProjectileActor를 만들고 
GameController에서 맵핑하는 테이블에는 유닛, 투사체를 구분하지 않고 한곳에 걍 저장

**Comment by suhyeokkim** [comment]
일단 고아 투사체는 고려하지 않고, 전부 삭제
