### ISSUE TITLE
UI 기본적인것만 붙이기

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#154]
담당자 : @suhyeokkim

**Comment by suhyeokkim** [comment]
## 일반적인 코딩 방법 (추가 예정)

1. 해상도 정한 후, 각각의 UI는 fixed rect 안에서 처리되어야함.

![image](https://user-images.githubusercontent.com/7834693/179506255-4b698739-f2b1-4393-93db-4c86d7ff9402.png)

위 그림은 부모의 뷰 크기와 실제 이미지를 그리는 부분이 다름. 이를 맞춰줘야함. 부모의 크기는 자식의 크기와도 연관되어 있음.

2. button 컴포넌트에 로직 관련 이벤트는 serialization 하지 않고, 코드에서 button 컴포넌트를 가져와 직접 제어함. 코드에서 로직을 확인할 수 있어야함.

``` csharp
[SerializedField]
Button _button;

void OnEnable()
{
    _button.onClick.AddListener(OnClick);
}

void OnDisable()
{
    _button.onClick.RemoveListener(OnClick);
}

void OnClick()
{
    // blabla..
}
```

3. UI 프리팹은 Resources/UI 폴더 안에 있어야함.
4. UI 프리팹의 이름은 UIVIew 를 상속받은 클래스의 이름 이어야함. 

![image](https://user-images.githubusercontent.com/7834693/179508509-e91d27a2-1da7-43fa-8154-6584839f9393.png)

5. 상태에서 UI 를 붙이고 싶으면 클래스에 이걸 붙여줌

``` csharp
// type 은 위의 규칙을 사용해 알아서 인스턴스 로드
// boolean 은 시 작하자 마자 보여주는 옵션
[UIBind(typeof(IntroView), true)]
public partial class IntroState : AppState
{
    ....
}
```

6. 상태에서 view 를 가져오려면 아래처럼함.

``` csharp
// type 은 위의 규칙을 사용해 알아서 인스턴스 로드
// boolean 은 시 작하자 마자 보여주는 옵션
[UIBind(typeof(IntroView), true)]
public partial class IntroState : AppState
{
    [InitializeMethod]
    public void Initialize()
    { 
        var view = GetView<IntroView>();
    }
}
```

**Comment by suhyeokkim** [comment]
#171 에서 함
