### ISSUE TITLE
업그레이드

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#48]
- 언락 조건 없음
- 독립적
- 선형
- 일단 비용 없음 (재화 시스템이 추가되면 나중에 붙임)
- 시간 필요(테이블에 작성 필요)

**Comment by suhyeokkim** [comment]
업그레이드 UI 연ㄴ결 해야될거 같은데ㅐ..

**Comment by suhyeokkim** [comment]
UnitUpgrade 에 딕셔너리 형태로만 되어서 따로 테이블 만듦
