### ISSUE TITLE
화면 스크롤

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#52]
# 논의 필요

유닛 움직이는 코드를 제거하면 당장 테스트를 해야해서 다른 움직이는 방법 정해서 대체해야함.

# 구현 사항?

- [x] 화면 스크롤 : 방향키 / 드래그
- [x] zoon in/out
- ~~[ ] 기존 방법을 대체할 유닛 움직일 방법?~~

**Comment by boyism80** [comment]
화면 스크롤 UX를 기준으로 기존 UX가 변경될 수 있음. (모바일 기준)
유닛을 직접 선택해서 조작하는 UX가 사라질 수 있음. UI에서 이 기능을 대체

**Comment by boyism80** [comment]
카메라 height 조절 기능 추가 (zoom in out)

**Comment by suhyeokkim** [comment]
유닛 움직이는 코드는 테스트 용으로 직접 넣기
