### ISSUE TITLE
플레이어

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#56]
- [x] 플레이어 스폰 위치 지정
- [x] 타겟 플레이어 지정
- [x] 플레이어 레벨
- [x] 업그레이드 플레이어 클래스로 이전
- [x] 타겟 플레이어 알아볼 수 있게

**Comment by suhyeokkim** [comment]
- 플레이어 스폰 위치 지정 : 유닛 스폰 위치 처리 추가
- 타겟 플레이어 지정 : 논의 필요, 위치로 갈지, 아니면  다른 방법으로 갈지, #60 에 적어놓음
- 플레이어 레벨 : 레벨 업 처리만함
- 업그레이드 플레이어 클래스로 이전 : OK
