### ISSUE TITLE
치트

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#58]
[BuildCommand("power overwhelming")]
public static void PowerOverwhelming(string value1, string value2) // 파라미터는 임의로 지정할 수 있도록 정의
{
    ....
}

사용예) power overwhelming 1 2

**Comment by boyism80** [comment]
채팅 완료 후 작업하면 됨

**Comment by suhyeokkim** [comment]
아 재밌겠다

**Comment by boyism80** [comment]
Chit -> Cheat
커스텀하게 파라미터 받도록 수정 필요
