### ISSUE TITLE
맵 데이터 파일로 관리

### ISSUE THREAD

**Issue by boyism80** [KG-Crash/crash#63]
- [x] 게임 시작하는 시점에 threshold를 기준으로 이동가능/불가 cell로 판단하는 대신 파일에서 그 정보를 읽어와 셋팅

**Comment by suhyeokkim** [comment]
그냥 무식하게 직렬/역직렬화는 너무 느려서 안됨. 최소한의 정보만 필요할 듯

UpdateWalkability 에서 처리 하는 부분만 저장

**Comment by suhyeokkim** [comment]
분리해서 저장했는데도 느리면 protobuf-net 써서 해야할듯
